// =========================================
// DONNÉES PRODUITS
// =========================================
const PRODUCTS = [
  {
    id: 1,
    name: "Écouteurs Bluetooth Sony WH-1000XM5",
    cat: "tech",
    catLabel: "High-Tech",
    desc: "Réduction de bruit active leader du marché. Autonomie 30h, son Hi-Res, ultra confort.",
    price: 279,
    oldPrice: 380,
    rating: 4.8,
    reviews: 4200,
    badge: "Meilleure vente",
    badgeClass: "",
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 2,
    name: "Robot Aspirateur Roborock S8",
    cat: "maison",
    catLabel: "Maison",
    desc: "Aspiration et lavage 2-en-1, navigation laser, cartographie multi-niveaux.",
    price: 499,
    oldPrice: 649,
    rating: 4.7,
    reviews: 1850,
    badge: "Promo",
    badgeClass: "deal",
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 3,
    name: "Manette PS5 DualSense Edge",
    cat: "gaming",
    catLabel: "Gaming",
    desc: "Manette pro ultra-personnalisable. Boutons arrière, profils, sticks remplaçables.",
    price: 209,
    oldPrice: 240,
    rating: 4.6,
    reviews: 980,
    badge: "Nouveau",
    badgeClass: "new",
    img: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 4,
    name: "Tapis de Course NordicTrack T8.5",
    cat: "sport",
    catLabel: "Sport",
    desc: "Vitesse 0–20 km/h, inclinaison 12%, écran 10\", connexion iFit incluse.",
    price: 899,
    oldPrice: 1099,
    rating: 4.5,
    reviews: 630,
    badge: "",
    badgeClass: "",
    img: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 5,
    name: "AirFryer Philips XXL 7.3L",
    cat: "cuisine",
    catLabel: "Cuisine",
    desc: "14 programmes, 7.3 litres pour toute la famille. Friture sans huile jusqu'à 200°C.",
    price: 199,
    oldPrice: 249,
    rating: 4.7,
    reviews: 3100,
    badge: "Meilleure vente",
    badgeClass: "",
    img: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 6,
    name: "Smartphone Samsung Galaxy S25",
    cat: "tech",
    catLabel: "High-Tech",
    desc: "Écran AMOLED 6.2\", puce Snapdragon 8 Elite, triple caméra 200MP, 5G.",
    price: 849,
    oldPrice: 999,
    rating: 4.8,
    reviews: 5600,
    badge: "Nouveau",
    badgeClass: "new",
    img: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 7,
    name: "Vélo Elliptique Proform Carbon EL",
    cat: "sport",
    catLabel: "Sport",
    desc: "20 niveaux de résistance, écran LCD, iFit intégré. Silencieux et pliable.",
    price: 449,
    oldPrice: 549,
    rating: 4.4,
    reviews: 420,
    badge: "",
    badgeClass: "",
    img: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 8,
    name: "Lampe LED de Bureau Benq ScreenBar",
    cat: "maison",
    catLabel: "Maison",
    desc: "Éclairage asymétrique anti-éblouissement, auto-dimming, USB-C, aucun reflet écran.",
    price: 109,
    oldPrice: 129,
    rating: 4.9,
    reviews: 2200,
    badge: "Top noté",
    badgeClass: "new",
    img: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 9,
    name: "Clavier Mécanique Keychron Q1 Pro",
    cat: "gaming",
    catLabel: "Gaming",
    desc: "Switches Gateron, aluminium CNC, sans fil Bluetooth, RGB per-key, QMK/VIA.",
    price: 179,
    oldPrice: 199,
    rating: 4.7,
    reviews: 860,
    badge: "",
    badgeClass: "",
    img: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 10,
    name: "Cafetière à Grain De'Longhi Magnifica",
    cat: "cuisine",
    catLabel: "Cuisine",
    desc: "Machine expresso automatique, moulin intégré, cappuccino, latte, 15 bar.",
    price: 699,
    oldPrice: 849,
    rating: 4.6,
    reviews: 1900,
    badge: "Promo",
    badgeClass: "deal",
    img: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 11,
    name: "Casque Gaming HyperX Cloud Alpha",
    cat: "gaming",
    catLabel: "Gaming",
    desc: "Son Dual Chamber, micro détachable, aluminium, compatible PC/PS/Xbox/Mobile.",
    price: 69,
    oldPrice: 99,
    rating: 4.5,
    reviews: 7800,
    badge: "Promo",
    badgeClass: "deal",
    img: "https://images.unsplash.com/photo-1599669454699-248893623440?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  },
  {
    id: 12,
    name: "Tapis Yoga Lululemon 5mm",
    cat: "sport",
    catLabel: "Sport",
    desc: "Matière antidérapante, 5mm d'épaisseur, sangle intégrée, résistant à l'humidité.",
    price: 88,
    oldPrice: 108,
    rating: 4.8,
    reviews: 3400,
    badge: "",
    badgeClass: "",
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80",
    link: "https://amzn.to/4bE3sLC"
  }
];
